### ISSUE TITLE
Regularly experiencing OOM running node even with 128gb RAM

### ISSUE THREAD

**Issue by meteozond** [InjectiveFoundation/injective-core#5]
I'm regularly experiencing OOM running node even with 128gb RAM
Version installed v1.12.1
Are there any tweaks could be done to reduce memory consumption?

**Comment by achilleas-kal** [comment]
@meteozond can you set the wasm cache to 3GB?

`injectived start --wasm.memory_cache_size 3000`

See here for more details: https://github.com/CosmWasm/cosmwasm/issues/1978

**Comment by meteozond** [comment]
@achilleas-kal Thangs! I'll give it a try! 
BTW Is there any chance of getting inj update with fixed version of CosmWasm?

**Comment by achilleas-kal** [comment]
We'll be making an upgrade early July and this should be fixed in the newer version.
